In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print('Libraries imported.')

Libraries imported.

In [35]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/glass/glass.data"
columns = ['id','RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','class']
df = pd.read_csv(url, names=columns)
df.head()

   id       RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  class
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0      1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0      1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0      1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0      1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0      1

In [36]:

X = df.iloc[:, 0:4]
y = df['id']
print(X.shape, y.shape)

(214, 4) (214,)

In [37]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

print('Train size:', X_train.shape)
print('Test size:', X_test.shape)

Train size: (149, 4)
Test size: (65, 4)

In [38]:

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
print('Model trained.')

Model trained.

In [39]:


y_pred = knn.predict(X_test)
list(y_pred)[:10]

[np.int64(8),
 np.int64(195),
 np.int64(64),
 np.int64(190),
 np.int64(116),
 np.int64(108),
 np.int64(14),
 np.int64(86),
 np.int64(75),
 np.int64(143)]

In [40]:
results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

results['Status'] = results.apply(lambda r: 'Correct' if r.Actual == r.Predicted else 'Wrong', axis=1)
results.head(20)

    Actual  Predicted Status
0       10          8  Wrong
1      198        195  Wrong
2       67         64  Wrong
3      192        190  Wrong
4      118        116  Wrong
5      112        108  Wrong
6       16         14  Wrong
7       87         86  Wrong
8       76         75  Wrong
9      145        143  Wrong
10     183        181  Wrong
11     171        169  Wrong
12     142        141  Wrong
13      74         72  Wrong
14     179        177  Wrong
15     168        167  Wrong
16     191        189  Wrong
17      19         18  Wrong
18      46         44  Wrong
19     185        182  Wrong

In [41]:

print('Accuracy:', accuracy_score(y_test, y_pred))
print('\nClassification Report:')
print(classification_report(y_test, y_pred))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.0

Classification Report:
              precision    recall  f1-score   support

           5       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       1.0
           8       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       1.0
          14       0.00      0.00      0.00       0.0
          16       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       1.0
          18       0.00      0.00      0.00       0.0
          19       0.00      0.00      0.00       1.0
          20       0.00      0.00      0.00       1.0
          23       0.00      0.00      0.00       0.0
          24       0.00      0.00      0.00       0.0
          25       0.00      0.00      0.00       1.0
          26       0.00      0.00      0.00       1.0
          28       0.00      0.00      0.00       0.0
          29       0.00      0.00      0.00       0.0
          30       0.00      0.00      0.00       1.0
          31       0.00      0.00      0.00       1.0
          37       0.00      0.00      0.00       0.0
          39       0.00      0.00      0.00       1.0
          44       0.00      0.00      0.00       0.0
          46       0.00      0.00      0.00       1.0
          54       0.00      0.00      0.00       0.0
          55       0.00      0.00      0.00       0.0
          56       0.00      0.00      0.00       1.0
          57       0.00      0.00      0.00       1.0
          59       0.00      0.00      0.00       0.0
          61       0.00      0.00      0.00       1.0
          64       0.00      0.00      0.00       0.0
          65       0.00      0.00      0.00       0.0
          66       0.00      0.00      0.00       0.0
          67       0.00      0.00      0.00       1.0
          68       0.00      0.00      0.00       1.0
          69       0.00      0.00      0.00       1.0
          70       0.00      0.00      0.00       1.0
          71       0.00      0.00      0.00       0.0
          72       0.00      0.00      0.00       0.0
          74       0.00      0.00      0.00       1.0
          75       0.00      0.00      0.00       0.0
          76       0.00      0.00      0.00       1.0
          78       0.00      0.00      0.00       0.0
          80       0.00      0.00      0.00       1.0
          83       0.00      0.00      0.00       0.0
          85       0.00      0.00      0.00       1.0
          86       0.00      0.00      0.00       0.0
          87       0.00      0.00      0.00       1.0
          92       0.00      0.00      0.00       0.0
          93       0.00      0.00      0.00       0.0
          94       0.00      0.00      0.00       1.0
          95       0.00      0.00      0.00       0.0
          96       0.00      0.00      0.00       1.0
          97       0.00      0.00      0.00       1.0
          98       0.00      0.00      0.00       1.0
          99       0.00      0.00      0.00       1.0
         100       0.00      0.00      0.00       0.0
         102       0.00      0.00      0.00       1.0
         103       0.00      0.00      0.00       0.0
         105       0.00      0.00      0.00       1.0
         108       0.00      0.00      0.00       0.0
         110       0.00      0.00      0.00       1.0
         112       0.00      0.00      0.00       1.0
         116       0.00      0.00      0.00       0.0
         118       0.00      0.00      0.00       1.0
         119       0.00      0.00      0.00       0.0
         120       0.00      0.00      0.00       1.0
         126       0.00      0.00      0.00       0.0
         127       0.00      0.00      0.00       0.0
         128       0.00      0.00      0.00       1.0
         129       0.00      0.00      0.00       1.0
         134       0.00      0.00      0.00       0.0
         135       0.00      0.00      0.00       0.0
         136       0.00      0.00      0.00       1.0
         137       0.00      0.00      0.00       1.0
         138       0.00      0.00      0.00       0.0
         139       0.00      0.00      0.00       1.0
         141       0.00      0.00      0.00       0.0
         142       0.00      0.00      0.00       1.0
         143       0.00      0.00      0.00       0.0
         145       0.00      0.00      0.00       1.0
         148       0.00      0.00      0.00       0.0
         149       0.00      0.00      0.00       1.0
         151       0.00      0.00      0.00       0.0
         153       0.00      0.00      0.00       1.0
         157       0.00      0.00      0.00       0.0
         159       0.00      0.00      0.00       1.0
         160       0.00      0.00      0.00       0.0
         162       0.00      0.00      0.00       1.0
         164       0.00      0.00      0.00       0.0
         165       0.00      0.00      0.00       1.0
         167       0.00      0.00      0.00       0.0
         168       0.00      0.00      0.00       1.0
         169       0.00      0.00      0.00       0.0
         171       0.00      0.00      0.00       1.0
         172       0.00      0.00      0.00       1.0
         173       0.00      0.00      0.00       0.0
         174       0.00      0.00      0.00       1.0
         175       0.00      0.00      0.00       0.0
         176       0.00      0.00      0.00       1.0
         177       0.00      0.00      0.00       0.0
         179       0.00      0.00      0.00       1.0
         181       0.00      0.00      0.00       0.0
         182       0.00      0.00      0.00       0.0
         183       0.00      0.00      0.00       1.0
         185       0.00      0.00      0.00       1.0
         186       0.00      0.00      0.00       1.0
         187       0.00      0.00      0.00       0.0
         189       0.00      0.00      0.00       0.0
         190       0.00      0.00      0.00       0.0
         191       0.00      0.00      0.00       1.0
         192       0.00      0.00      0.00       1.0
         194       0.00      0.00      0.00       0.0
         195       0.00      0.00      0.00       0.0
         196       0.00      0.00      0.00       1.0
         197       0.00      0.00      0.00       0.0
         198       0.00      0.00      0.00       1.0
         199       0.00      0.00      0.00       0.0
         200       0.00      0.00      0.00       1.0
         201       0.00      0.00      0.00       1.0
         203       0.00      0.00      0.00       0.0
         204       0.00      0.00      0.00       1.0
         208       0.00      0.00      0.00       0.0
         210       0.00      0.00      0.00       1.0
         211       0.00      0.00      0.00       0.0
         212       0.00      0.00      0.00       1.0

    accuracy                           0.00      65.0
   macro avg       0.00      0.00      0.00      65.0
weighted avg       0.00      0.00      0.00      65.0


Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In this assignment, the k-Nearest Neighbour (kNN) algorithm was successfully implemented to perform classification on a dataset similar to the Iris dataset. The dataset was first explored and divided into training and testing subsets to evaluate the model’s performance on unseen data.

Using k = 3, the kNN classifier was able to correctly classify most of the test samples, achieving a high accuracy. The confusion matrix and classification report further confirmed that the model performed well across all classes, with only a small number of misclassifications. This indicates that kNN is effective for datasets with well-separated classes and numerical features.